repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: shellcheck
        name: ShellCheck
        entry: shellcheck
        language: system
        types: [shell]
    -   id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
    -   id: swiftlint
        name: SwiftLint
        entry: "swiftlint --quiet"
        language: system
        types: [swift]
