name: mdump
options:
  bundleIdPrefix: com.mdump
  deploymentTarget:
    macOS: 13.0
settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: time
    DEAD_CODE_STRIPPING: true
    ENABLE_MODULE_VERIFIER: true
    ENABLE_USER_SCRIPT_SANDBOXING: true
    GENERATE_INFOPLIST_FILE: true
    MODULE_VERIFIER_SUPPORTED_LANGUAGES: objective-c objective-c++
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: gnu11 gnu++14

targets:
  MDCoreSimulator:
    type: framework
    platform: macOS
    sources: Sources/MDCoreSimulator
    headers: Sources/MDCoreSimulator
    dependencies:
      - target: MDFramework
  MDCoreSimulatorTests:
    type: bundle.unit-test
    platform: macOS
    sources: Tests/MDCoreSimulatorTests
    dependencies:
      - target: MDCoreSimulator
    info:
      path: Tests/MDCoreSimulatorTests/Info.plist
      properties:
        NSPrincipalClass: MDCoreSimulatorTests.SetupTests
  MDFramework:
    type: framework
    platform: macOS
    sources: Sources/MDFramework
    headers: Sources/MDFramework
