//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef _SimDeallocSentinel_h
#define _SimDeallocSentinel_h
@import Foundation;

@interface _SimDeallocSentinel : NSObject

@property (nonatomic) BOOL called;
@property (copy, nonatomic) id /* block */ notCalledHandler;

/* instance methods */
- (void)dealloc;
@end

#endif /* _SimDeallocSentinel_h */
