//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef NSArray_SimPasteboardItem_h
#define NSArray_SimPasteboardItem_h
@import Foundation;

#include "NSPasteboardItemDataProvider-Protocol.h"

@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSPasteboardItem, NSString, NSString",?;

@interface NSArray (SimPasteboardItem)
/* class methods */
+ (id)denylistedTypes;

/* instance methods */
- (id)filterWithBlock:(id /* block */)block;
@end

#endif /* NSArray_SimPasteboardItem_h */
