//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef NSPasteboardItem_SimPasteboardItem_h
#define NSPasteboardItem_SimPasteboardItem_h
@import Foundation;

#include "NSPasteboardItemDataProvider-Protocol.h"

@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSPasteboardItem, NSString, NSString",?;

@interface NSPasteboardItem (SimPasteboardItem)
/* instance methods */
- (BOOL)setSimPBItemValue:(id)value forType:(id)type;
- (void)resolveAllTypes;
@end

#endif /* NSPasteboardItem_SimPasteboardItem_h */
