//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDevicePasteboardConnection_h
#define SimDevicePasteboardConnection_h
@import Foundation;

@class SimMachPort;

@interface SimDevicePasteboardConnection : NSObject

@property (retain, nonatomic) SimMachPort *pasteboardSupportPort;
@property (retain, nonatomic) SimMachPort *pasteboardPromiseSupportPort;

/* instance methods */
- (id)initWithDevice:(id)device;
- (id)createPortWithDevice:(id)device serviceName:(id)name;
- (BOOL)subscribeWithCallbackPort:(id)port changeCount:(unsigned long long *)count itemsDatatypes:(id *)datatypes error:(id *)error;
- (id)readDataArrayWithTypes:(id)types changeCount:(unsigned long long *)count error:(id *)error;
- (unsigned long long)writeDataArray:(id)array dataProviderPort:(id)port error:(id *)error;
- (id)readDataWithType:(id)type itemIndex:(unsigned long long)index changeCount:(unsigned long long)count error:(id *)error;
- (id)convertDataWithType:(id)type data:(id)data toType:(id)type error:(id *)error;
- (void)refreshPasteboard;
@end

#endif /* SimDevicePasteboardConnection_h */
