//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDiskImage_h
#define SimDiskImage_h
@import Foundation;

#include "SimDiskImageIdentifier.h"
#include "SimDiskImageRuntimeInfo.h"

@class NSDate, NSDictionary, NSError, NSNumber, NSString, NSURL;

@interface SimDiskImage : NSObject

@property (retain, nonatomic) SimDiskImageIdentifier *identifier;
@property (retain, nonatomic) NSURL *imageURL;
@property (copy, nonatomic) NSString *userInterfaceDescription;
@property (nonatomic) unsigned long long imageState;
@property (nonatomic) unsigned long long unusableSubstate;
@property (retain, nonatomic) NSError *unusableError;
@property (nonatomic) BOOL deletable;
@property (retain, nonatomic) NSURL *mountURL;
@property (copy, nonatomic) NSNumber *sizeBytes;
@property (nonatomic) unsigned long long imageKind;
@property (retain, nonatomic) SimDiskImageRuntimeInfo *runtimeInfo;
@property (retain, nonatomic) NSDictionary *userInfo;
@property (nonatomic) unsigned long long signatureState;
@property (nonatomic) unsigned long long imageFormat;
@property (nonatomic) unsigned long long imageWritePolicy;
@property (nonatomic) unsigned long long imageMountPolicy;
@property (nonatomic) BOOL expandable;
@property (retain, nonatomic) NSDate *lastUsedAt;
@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *unusableErrorMessage;
@property (readonly, nonatomic) NSString *unusableErrorDetail;

/* instance methods */
- (id)initWithIdentifier:(id)identifier imageURL:(id)url imageState:(unsigned long long)state unusableSubstate:(unsigned long long)substate unusableError:(id)error deletable:(BOOL)deletable expandable:(BOOL)expandable mountURL:(id)url sizeBytes:(id)bytes imageKind:(unsigned long long)kind runtimeInfo:(id)info signatureState:(unsigned long long)state imageFormat:(unsigned long long)format imageWritePolicy:(unsigned long long)policy imageMountPolicy:(unsigned long long)policy lastUsedAt:(id)at userInfo:(id)info;
- (id)initFromXPCDictionary:(id)xpcdictionary error:(id *)error;
- (id)description;
@end

#endif /* SimDiskImage_h */
