//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceIOServerLogger_h
#define SimDeviceIOServerLogger_h
@import Foundation;

#include "SimDeviceIOLogger-Protocol.h"

@class NSString, NSString",?;

@interface SimDeviceIOServerLogger : NSObject<SimDeviceIOLogger>

@property (copy, nonatomic) NSString *bundleIdentifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* instance methods */
- (id)initForBundleIdentifier:(id)identifier;
- (void)deviceIOLogLevel:(int)level message:(id)message;
- (void)deviceIOLogError:(id)error message:(id)message;
@end

#endif /* SimDeviceIOServerLogger_h */
