//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceIOLoadedBundle_h
#define SimDeviceIOLoadedBundle_h
@import Foundation;

@class NSBundle;
@protocol SimDeviceIOBundleInterface;

@interface SimDeviceIOLoadedBundle : NSObject

@property (retain, nonatomic) NSBundle *bundle;
@property (retain, nonatomic) NSObject<SimDeviceIOBundleInterface> *bundleInterface;

/* class methods */
+ (id)loadedBundleForURL:(id)url;

/* instance methods */
- (id)initWithURL:(id)url;
@end

#endif /* SimDeviceIOLoadedBundle_h */
