//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceBootInfo_h
#define SimDeviceBootInfo_h
@import Foundation;

#include "NSObjectROCKDeserializable-Protocol.h"
#include "NSObjectROCKSerializable-Protocol.h"

@class NSDictionary, NSString, NSString",?;

@interface SimDeviceBootInfo : NSObject<NSObjectROCKDeserializable, NSObjectROCKSerializable>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;
@property (nonatomic) unsigned int status;
@property (nonatomic) double bootElapsedTime;
@property (nonatomic) BOOL isTerminalStatus;
@property (retain, nonatomic) NSDictionary *info;
@property (readonly, nonatomic) NSString *migrationPhaseDescription;
@property (readonly, nonatomic) double migrationElapsedTime;
@property (readonly, nonatomic) NSDictionary *migrationPluginDetails;

/* class methods */
+ (id)rockDecodeWithXPCObject:(id)xpcobject sessionManager:(id)manager error:(id *)error;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)rockEncodeWithSessionManager:(id)manager error:(id *)error;
- (id)initWithElapsedTime:(double)time status:(unsigned int)status info:(id)info;
- (BOOL)isEqual:(id)equal;
@end

#endif /* SimDeviceBootInfo_h */
