//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDevicePasteboardItem_h
#define SimDevicePasteboardItem_h
@import Foundation;

#include "SimPasteboardItem.h"
#include "SimDevicePasteboardConnection.h"
#include "SimPasteboardItemDataProvider-Protocol.h"

@class NSString, NSString",?;

@interface SimDevicePasteboardItem : SimPasteboardItem<SimPasteboardItemDataProvider>

@property (retain, nonatomic) SimDevicePasteboardConnection *connection;
@property (nonatomic) unsigned long long pasteboardChangeCount;
@property (nonatomic) unsigned long long pasteboardItemIndex;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* instance methods */
- (id)initWithConnection:(id)connection changeCount:(unsigned long long)count itemIndex:(unsigned long long)index itemData:(id)data;
- (id)nsPasteboardRepresentation;
- (id)retrieveValueForSimPasteboardItem:(id)item type:(id)type;
- (void)pasteboard:(id)pasteboard item:(id)item provideDataForType:(id)type;
- (id)transformValueWithType:(id)type value:(id)value;
@end

#endif /* SimDevicePasteboardItem_h */
