//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceIO_h
#define SimDeviceIO_h
@import Foundation;

#include "SimDevice.h"
#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimDeviceIOInterface-Protocol.h"
#include "SimDeviceIOProtocol-Protocol.h"
#include "SimDeviceIORuntimeInterface-Protocol.h"

@class NSArray, NSString, NSString",?, NSURL, NSUUID;
@protocol OS_dispatch_queue;

@interface SimDeviceIO : NSObject<SimDeviceIOInterface, SimDeviceIOProtocol>

@property (weak, nonatomic) SimDevice *device;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *errorQueue;
@property (copy, nonatomic) id /* block */ errorHandler;
@property (readonly, nonatomic) NSUUID *deviceUDID;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) NSObject<SimDeviceIORuntimeInterface> *deviceRuntime;
@property (readonly, nonatomic) NSObject<SimDeviceIODeviceTypeInterface> *deviceType;
@property (readonly, nonatomic) NSURL *deviceDataURL;
@property (readonly, nonatomic) NSURL *deviceLogURL;
@property (readonly, nonatomic) NSArray *ioPorts;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* class methods */
+ (id)ioForSimDevice:(id)device errorQueue:(id)queue errorHandler:(id /* block */)handler;

/* instance methods */
- (id)initWithDevice:(id)device errorQueue:(id)queue errorHandler:(id /* block */)handler;
- (id)ioPortForUUID:(id)uuid;
- (BOOL)registerPort:(unsigned int)port service:(id)service error:(id *)error;
- (BOOL)unregisterService:(id)service error:(id *)error;
- (BOOL)postDarwinNotification:(id)notification error:(id *)error;
- (BOOL)getDarwinNotificationState:(unsigned long long *)state name:(id)name error:(id *)error;
- (BOOL)setDarwinNotificationState:(unsigned long long)state name:(id)name error:(id *)error;
- (BOOL)postHostNotification:(id)notification portUUID:(id)uuid portClass:(unsigned short)class info:(id)info error:(id *)error;
- (BOOL)supportsFeature:(id)feature;
- (void)connectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)disconnectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
@end

#endif /* SimDeviceIO_h */
