//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDiskImageRuntimeInfo_h
#define SimDiskImageRuntimeInfo_h
@import Foundation;

@class NSString, NSURL;

@interface SimDiskImageRuntimeInfo : NSObject

@property (copy, nonatomic) NSString *runtimeIdentifier;
@property (retain, nonatomic) NSURL *runtimeBundleURL;
@property (copy, nonatomic) NSString *platformIdentifier;
@property (copy, nonatomic) NSString *versionString;
@property (copy, nonatomic) NSString *buildVersionString;
@property (nonatomic) BOOL isInternal;
@property (readonly, nonatomic) NSString *platformName;

/* class methods */
+ (id)platformNameForIdentifier:(id)identifier;

/* instance methods */
- (id)initWithIdentifier:(id)identifier runtimeBundleURL:(id)url platformIdentifier:(id)identifier versionString:(id)string buildVersionString:(id)string isInternal:(BOOL)internal;
- (id)initFromXPCDictionary:(id)xpcdictionary error:(id *)error;
- (id)description;
@end

#endif /* SimDiskImageRuntimeInfo_h */
