//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceType_h
#define SimDeviceType_h
@import Foundation;

#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimProfileBundle.h"

@class NSArray, NSDictionary, NSString, NSString",?, NSURL;
@protocol OS_dispatch_queue>",?;

@interface SimDeviceType : NSObject<SimDeviceIODeviceTypeInterface>

@property (retain, nonatomic) SimProfileBundle *bundle;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *modelIdentifier;
@property (nonatomic) struct CGSize { double x0; double x1; } mainScreenSize;
@property (nonatomic) struct CGSize { double x0; double x1; } mainScreenDPI;
@property (nonatomic) struct CGSize { double x0; double x1; } defaultCanvasSize;
@property (nonatomic) float mainScreenScale;
@property (nonatomic) unsigned int mainScreenColorspace;
@property (copy, nonatomic) NSURL *framebufferMaskURL;
@property (copy, nonatomic) NSURL *sensorBarImageURL;
@property (copy, nonatomic) NSArray *supportedArchs;
@property (copy, nonatomic) NSArray *supportedArchStrings;
@property (nonatomic) unsigned int minRuntimeVersion;
@property (nonatomic) unsigned int maxRuntimeVersion;
@property (nonatomic) unsigned int minCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int maxCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int createByDefaultForRuntimeVersionMin;
@property (nonatomic) unsigned int createByDefaultForRuntimeVersionMax;
@property (nonatomic) unsigned int pairByDefaultForRuntimeVersionMin;
@property (nonatomic) unsigned int pairByDefaultForRuntimeVersionMax;
@property (copy, nonatomic) NSString *springBoardConfigName;
@property (copy, nonatomic) NSString *productClass;
@property (copy, nonatomic) NSArray *supportedProductFamilyIDs;
@property (copy, nonatomic) NSDictionary *environment_extra;
@property (copy, nonatomic) NSDictionary *capabilities;
@property (copy, nonatomic) NSArray *aliases;
@property (copy, nonatomic) NSDictionary *supportedFeatures;
@property (copy, nonatomic) NSDictionary *supportedFeaturesConditionalOnRuntime;
@property (retain, nonatomic) NSString *chromeIdentifier;
@property (retain, nonatomic) NSString *userInterfaceIdentifier;
@property (readonly, nonatomic) int productFamilyID;
@property (readonly, nonatomic) NSString *productFamily;
@property (readonly, nonatomic) NSURL *bundleURL;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue>",? *memoizableSerializerQueue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* instance methods */
- (id)initWithBundle:(id)bundle error:(id *)error;
- (id)bundlePath;
- (id)environment;
- (BOOL)supportsFeature:(id)feature;
- (BOOL)supportsFeatureConditionally:(id)conditionally;
- (long long)compare:(id)compare;
- (Class)deviceClass;
@end

#endif /* SimDeviceType_h */
