//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceIOServer_h
#define SimDeviceIOServer_h
@import Foundation;

#include "SimDeviceIO.h"
#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimDeviceIOInterface-Protocol.h"
#include "SimDeviceIORuntimeInterface-Protocol.h"

@class NSArray, NSDictionary, NSError, NSString, NSString",?, NSURL, NSUUID;

@interface SimDeviceIOServer : SimDeviceIO<SimDeviceIOInterface> {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
  atomic long long _loadGeneration;
}

@property (retain, nonatomic) NSArray *ioPorts;
@property (retain, nonatomic) NSArray *connectedPorts;
@property (retain, nonatomic) NSArray *connectedBundles;
@property (retain, nonatomic) NSDictionary *loadedBundles;
@property (retain, nonatomic) NSDictionary *loadedBundlesByPortUUID;
@property (retain, nonatomic) NSError *bundleLoadError;
@property (nonatomic) BOOL hasPreparedForShutdown;
@property (nonatomic) BOOL hasNotifiedDidShutdown;
@property (readonly, nonatomic) NSUUID *deviceUDID;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) NSObject<SimDeviceIORuntimeInterface> *deviceRuntime;
@property (readonly, nonatomic) NSObject<SimDeviceIODeviceTypeInterface> *deviceType;
@property (readonly, nonatomic) NSURL *deviceDataURL;
@property (readonly, nonatomic) NSURL *deviceLogURL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* class methods */
+ (id)discoverBundleDependencies:(id)dependencies;

/* instance methods */
- (BOOL)loadAllBundlesWithError:(id *)error;
- (void)_criticalError:(id)error inLoadGeneration:(long long)generation fromBundle:(id)bundle recoveryStrategy:(unsigned long long)strategy;
- (BOOL)prepareForBootWithOptions:(id)options error:(id *)error;
- (void)notifyDeviceDidBoot;
- (void)prepareForShutdown;
- (void)notifyDeviceDidShutdown;
- (void)unloadAllBundles;
- (id)legacyHIDDescriptorState;
- (id)internalDisplayDescriptorState;
- (id)externalDisplayDescriptorState;
- (id)audioHostRouteDescriptorState;
- (void)connectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)disconnectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (BOOL)registerPort:(unsigned int)port service:(id)service error:(id *)error;
- (BOOL)unregisterService:(id)service error:(id *)error;
- (BOOL)postDarwinNotification:(id)notification error:(id *)error;
- (BOOL)getDarwinNotificationState:(unsigned long long *)state name:(id)name error:(id *)error;
- (BOOL)setDarwinNotificationState:(unsigned long long)state name:(id)name error:(id *)error;
- (BOOL)postHostNotification:(id)notification portUUID:(id)uuid portClass:(unsigned short)class info:(id)info error:(id *)error;
@end

#endif /* SimDeviceIOServer_h */
