//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDiskImageIdentifier_h
#define SimDiskImageIdentifier_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSString;

@interface SimDiskImageIdentifier : NSObject<NSCopying>

@property (copy, nonatomic) NSString *opaqueValue;

/* instance methods */
- (id)initWithOpaqueValue:(id)value;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
@end

#endif /* SimDiskImageIdentifier_h */
