//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDevicePasteboard_h
#define SimDevicePasteboard_h
@import Foundation;

#include "SimDevice.h"
#include "SimDeviceNotificationManager.h"
#include "SimDevicePasteboardConnection.h"
#include "SimMachPortServer.h"
#include "SimPasteboard-Protocol.h"

@class NSArray, NSDate;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimDevicePasteboard : NSObject<SimPasteboard> {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _itemsLock;
}

@property unsigned long long changeCount;
@property (retain) NSArray *items;
@property (weak) SimDevice *device;
@property (retain) SimDevicePasteboardConnection *pasteboardConnection;
@property (retain) SimMachPortServer *notificationServer;
@property (retain, nonatomic) SimDeviceNotificationManager *notificationManager;
@property (nonatomic) unsigned long long bootMonitorRegistrationID;
@property (retain) SimMachPortServer *promisedDataServer;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *subscriptionStateQueue;
@property (retain, nonatomic) NSDate *lastConnectionTime;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *lifecycleSource;
@property (retain) NSArray *stagedItems;

/* instance methods */
- (id)initWithDevice:(id)device;
- (void)dealloc;
- (id)description;
- (void)_onSubscriptionStateQueue_subscribe;
- (void)startMonitorLifecyclePort;
- (void)addDisconnectMonitorPort:(unsigned int)port;
- (void)_onSubscriptionStateQueue_unsubscribe;
- (void)pasteboardHasChanged:(unsigned long long)changed itemsTypes:(id)types;
- (void)setItems:(id)items changeCount:(unsigned long long)count;
- (id)generateSimPasteboardItemsWithTypes:(id)types changeCount:(unsigned long long)count;
- (void)itemsFromPasteboardAsyncWithTypes:(id)types completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (id)itemsFromPasteboardWithTypes:(id)types error:(id *)error;
- (void)setPasteboardAsyncWithItems:(id)items completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (unsigned long long)setPasteboardWithItems:(id)items error:(id *)error;
- (void)syncBarrier;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (BOOL)unregisterNotificationHandler:(unsigned long long)handler error:(id *)error;
@end

#endif /* SimDevicePasteboard_h */
