//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceIODeviceTypeInterface_Protocol_h
#define SimDeviceIODeviceTypeInterface_Protocol_h
@import Foundation;

@protocol SimDeviceIODeviceTypeInterface <ROCKMemoizable>

@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *identifier;
@property (readonly, nonatomic) NSDictionary *capabilities;
@property (readonly, nonatomic) NSURL *framebufferMaskURL;
@property (readonly, nonatomic) NSString *chromeIdentifier;
@property (readonly, nonatomic) float mainScreenScale;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } mainScreenSize;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } mainScreenDPI;
@property (readonly, nonatomic) unsigned int mainScreenColorspace;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } defaultCanvasSize;
@property (readonly, nonatomic) unsigned int minRuntimeVersion;
@property (readonly, nonatomic) unsigned int maxRuntimeVersion;
@property (readonly, nonatomic) NSURL *bundleURL;

/* instance methods */
- (BOOL)supportsFeature:(id)feature;
- (BOOL)supportsFeatureConditionally:(id)conditionally;
@end

#endif /* SimDeviceIODeviceTypeInterface_Protocol_h */
