//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimDeviceDataMigrationPluginResult_h
#define SimDeviceDataMigrationPluginResult_h
@import Foundation;

@class NSString;

@interface SimDeviceDataMigrationPluginResult : NSObject

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *bundlePath;
@property (nonatomic) double duration;
@property (copy, nonatomic) NSString *phaseDescription;
@property (nonatomic) BOOL isSuccess;
@property (nonatomic) unsigned int status;
@property (readonly, nonatomic) NSString *component;

/* instance methods */
- (id)initWithIdentifier:(id)identifier info:(id)info;
- (id)description;
@end

#endif /* SimDeviceDataMigrationPluginResult_h */
