//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimHostResourceChecker_h
#define SimHostResourceChecker_h
@import Foundation;

@interface SimHostResourceChecker : NSObject
/* instance methods */
- (unsigned long long)maxUserProcs;
- (unsigned long long)runningUserProcs;
- (unsigned long long)maxSystemProcs;
- (unsigned long long)runningSystemProcs;
- (unsigned long long)maxFiles;
- (unsigned long long)openFiles;
- (unsigned long long)systemMemory;
- (BOOL)isSafeToBootWithError:(id *)error;
@end

#endif /* SimHostResourceChecker_h */
