//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimIdentityManager_h
#define SimIdentityManager_h
@import Foundation;

#include "SimIdentitySystem-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, NSString",?;
@protocol OS_dispatch_queue;

@interface SimIdentityManager : NSObject<SimIdentitySystem>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSMutableDictionary *devices;
@property (retain, nonatomic) NSArray *pendingRequests;
@property (nonatomic) BOOL hasPendingRequestCompletion;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *stateProtectionQueue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)deviceSetCreated:(id)created;
- (void)_onQueue_checkDeviceSetForNewDevices:(id)devices;
- (void)_onQueue_addDevice:(id)device;
- (void)_onQueue_removeDevice:(id)device;
- (void)_onQueue_deviceDidShutdown:(id)shutdown;
- (void)_onQueue_peerHandler:(id)handler peer:(id)peer;
- (void)enqueueRequestOperation:(id /* block */)operation forIdentityDevice:(id)device;
- (void)cancelQueuedOperationForIdentityDevice:(id)device;
- (void)_onQueue_processNextQueuedRequest;
@end

#endif /* SimIdentityManager_h */
