//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimIdentityDevice_h
#define SimIdentityDevice_h
@import Foundation;

#include "SimIdentitySystem-Protocol.h"

@class NSArray, NSData, NSSet, NSString;
@protocol OS_dispatch_queue, SimDeviceProtocol;

@interface SimIdentityDevice : NSObject

@property (weak, nonatomic) NSObject<SimIdentitySystem> *identitySystem;
@property (copy, nonatomic) NSString *keychainLabel;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSSet *clients;
@property (retain, nonatomic) NSArray *certificates;
@property (retain, nonatomic) NSData *privateKeyPersistentRef;
@property (weak, nonatomic) NSObject<SimDeviceProtocol> *simDevice;

/* instance methods */
- (id)initWithIdentitySystem:(id)system simDevice:(id)device;
- (void)dealloc;
- (void)peerConnected:(id)connected;
- (void)removeClient:(id)client;
- (void)deviceDidShutdown;
- (void)deleteExistingCertificateAndKeys;
- (void)requestCertificateWithCompletionQueue:(id)queue completionHandler:(id /* block */)handler;
- (id)_createKeySecAccessControlWithError:(id *)error;
- (void)_executeRequestOperation_withCompletionQueue:(id)queue completionHandler:(id /* block */)handler;
- (id)signData:(id)data privateKeyPersistentRef:(id)ref algorithm:(struct __CFString *)algorithm error:(id *)error;
@end

#endif /* SimIdentityDevice_h */
