//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimIdentitySystem_Protocol_h
#define SimIdentitySystem_Protocol_h
@import Foundation;

@protocol SimIdentitySystem <NSObject>

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *stateProtectionQueue;

/* instance methods */
- (void)enqueueRequestOperation:(id /* block */)operation forIdentityDevice:(id)device;
- (void)cancelQueuedOperationForIdentityDevice:(id)device;
@end

#endif /* SimIdentitySystem_Protocol_h */
