//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimIdentityClient_h
#define SimIdentityClient_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"
#include "SimIdentityDevice.h"
#include "SimIdentitySystem-Protocol.h"

@protocol OS_dispatch_queue;

@interface SimIdentityClient : NSObject

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property (weak, nonatomic) NSObject<SimIdentitySystem> *identitySystem;
@property (weak, nonatomic) SimIdentityDevice *identityDevice;

/* instance methods */
- (id)initWithNewPeer:(id)peer identityDevice:(id)device identitySystem:(id)system;
- (void)_onQueue_handleMessage:(id)message;
@end

#endif /* SimIdentityClient_h */
