//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimKnownSDKEntry_h
#define SimKnownSDKEntry_h
@import Foundation;

#include "SimPlatformInfo.h"
#include "SimSDKInfo.h"

@interface SimKnownSDKEntry : NSObject

@property (retain, nonatomic) SimPlatformInfo *platform;
@property (retain, nonatomic) SimSDKInfo *sdk;

/* class methods */
+ (id)entryWithPlatform:(id)platform sdk:(id)sdk;

/* instance methods */
@end

#endif /* SimKnownSDKEntry_h */
