//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimLibLaunchInstance_h
#define SimLibLaunchInstance_h
@import Foundation;

#include "SimLaunchHostConnection.h"

@class NSURL, NSUUID;

@interface SimLibLaunchInstance : NSObject

@property (retain, nonatomic) NSUUID *libLaunchUUID;
@property (retain, nonatomic) NSURL *libLaunchURL;
@property (nonatomic) unsigned int equivalentIOSVersion;
@property (weak, nonatomic) SimLaunchHostConnection *connection;

/* instance methods */
- (id)initWithLibLaunchURL:(id)url equivalentIOSVersion:(unsigned int)iosversion connection:(id)connection;
- (void)dealloc;
@end

#endif /* SimLibLaunchInstance_h */
