//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimLocalThrowable_h
#define SimLocalThrowable_h
@import Foundation;

@interface SimLocalThrowable : NSObject

@property (retain, nonatomic) id data;

/* class methods */
+ (id)throwableWithData:(id)data;

/* instance methods */
- (id)initWithData:(id)data;
@end

#endif /* SimLocalThrowable_h */
