//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimLaunchHostClient_h
#define SimLaunchHostClient_h
@import Foundation;

#include "SimLaunchHostConnection.h"
#include "SimLibLaunchInstance.h"

@interface SimLaunchHostClient : NSObject {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (retain, nonatomic) SimLaunchHostConnection *connection;
@property (retain, nonatomic) SimLibLaunchInstance *libLaunchInstance;

/* class methods */
+ (id)launchHostClientForRuntime:(id)runtime error:(id *)error;

/* instance methods */
- (id)initWithConnection:(id)connection libLaunchInstance:(id)instance error:(id *)error;
- (BOOL)_parseErrorReply:(id)reply error:(id *)error;
- (BOOL)startNewSession:(id)session endpointsToRegister:(id)register bindPort:(unsigned int)port deathQueue:(id)queue deathHandler:(id /* block */)handler error:(id *)error;
- (BOOL)registerServiceInSession:(id)session serviceName:(id)name servicePort:(unsigned int)port error:(id *)error;
- (BOOL)unregisterServiceFromSession:(id)session serviceName:(id)name error:(id *)error;
- (BOOL)findServiceInSession:(id)session serviceName:(id)name servicePort:(unsigned int *)port error:(id *)error;
- (id)getEnvValueInSession:(id)session named:(id)named;
- (BOOL)spawnInSession:(id)session program:(id)program arguments:(id)arguments environment:(id)environment cwd:(id)cwd standardInput:(id)input standardOutput:(id)output standardError:(id)error binpref:(int)binpref flags:(unsigned long long)flags pid:(int *)pid terminationQueue:(id)queue terminationHandler:(id /* block */)handler error:(id *)error;
@end

#endif /* SimLaunchHostClient_h */
