//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimLaunchHostConnection_h
#define SimLaunchHostConnection_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"

@class NSMapTable, NSString;
@protocol OS_dispatch_queue;

@interface SimLaunchHostConnection : NSObject

@property (copy, nonatomic) NSString *serviceName;
@property (retain, nonatomic) NSObject<OS_xpc_object> *xpcConnection;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSMapTable *libLaunchInstances;
@property (nonatomic) BOOL pendingResync;

/* class methods */
+ (BOOL)parseErrorReply:(id)reply error:(id *)error;
+ (id)allJobLabels;
+ (id)connectionForArch:(id)arch error:(id *)error;

/* instance methods */
- (id)initWithServiceName:(id)name;
- (void)dealloc;
- (void)_checkAndResyncIfNeeded;
- (id)loadLibLaunchAtURL:(id)url equivalentIOSVersion:(unsigned int)iosversion error:(id *)error;
- (void)unloadLibLaunch:(id)launch;
- (void)sendMessage:(id)message;
- (id)sendMessageSyncWithReply:(id)reply;
- (void)sendMessage:(id)message replyQueue:(id)queue replyHandler:(id /* block */)handler;
- (void)_instanceWillDealloc:(id)dealloc;
- (void)_onQueue_launchInstanceUnload:(id)unload;
- (id)_loadRequestForInstance:(id)instance existingUUID:(id)uuid;
- (id)_sendLoadRequestForInstance:(id)instance existingUUID:(id)uuid error:(id *)error;
- (void)_onQueue_sendAsyncLoadRequestForInstance:(id)instance existingUUID:(id)uuid completionQueue:(id)queue completionHandler:(id /* block */)handler;
@end

#endif /* SimLaunchHostConnection_h */
