//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimMachPortServer_h
#define SimMachPortServer_h
@import Foundation;

@class NSString, SimMachPort;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimMachPortServer : NSObject

@property (retain, nonatomic) SimMachPort *port;
@property (retain, nonatomic) NSString *name;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *serverQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *serverSource;

/* instance methods */
- (id)initWithName:(id)name machMessageHandler:(undefined *)handler machMessageSize:(unsigned int)size;
- (id)description;
@end

#endif /* SimMachPortServer_h */
