//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNearbyDevice_h
#define SimNearbyDevice_h
@import Foundation;

@class NSMutableArray;
@protocol SimDeviceProtocol;

@interface SimNearbyDevice : NSObject

@property (retain, nonatomic) NSObject<SimDeviceProtocol> *device;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } deviceRect;
@property (nonatomic) double deviceRotation;
@property (nonatomic) BOOL hasPendingUpdate;
@property (retain, nonatomic) NSMutableArray *clients;

/* instance methods */
- (id)initWithDevice:(id)device;
@end

#endif /* SimNearbyDevice_h */
