//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNSPasteboard_h
#define SimNSPasteboard_h
@import Foundation;

#include "SimDeviceNotificationManager.h"
#include "SimPasteboard-Protocol.h"

@class NSArray, NSPasteboard;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimNSPasteboard : NSObject<SimPasteboard>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *nsPasteboardQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *pollPasteboardChangeTimer;
@property (retain) NSArray *items;
@property unsigned long long changeCount;
@property (retain, nonatomic) NSPasteboard *nsPasteboard;
@property (retain, nonatomic) SimDeviceNotificationManager *notificationManager;
@property unsigned long long refreshResolveCount;

/* class methods */
+ (id)pasteboardForNSPasteboard:(id)nspasteboard refreshResolveCount:(unsigned long long)count;

/* instance methods */
- (id)initWithNSPasteboard:(id)nspasteboard refreshResolveCount:(unsigned long long)count;
- (void)dealloc;
- (id)description;
- (void)refreshItemsFromNSPasteboardWithForcedRefresh:(BOOL)refresh;
- (void)sendPasteboardChangedNotification;
- (void)syncBarrier;
- (void)setPasteboardAsyncWithItems:(id)items completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (unsigned long long)setPasteboardWithItems:(id)items error:(id *)error;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (BOOL)unregisterNotificationHandler:(unsigned long long)handler error:(id *)error;
@end

#endif /* SimNSPasteboard_h */
