//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNotificationManager_h
#define SimNotificationManager_h
@import Foundation;

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface SimNotificationManager : NSObject

@property (copy, nonatomic) NSString *name;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *handlersQueue;
@property (retain, nonatomic) NSMutableDictionary *handlers;
@property (nonatomic) unsigned long long next_regID;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sendQueue;

/* class methods */
+ (Class)registrationTokenClass;

/* instance methods */
- (id)initWithName:(id)name;
- (id)registerNotificationHandler:(id /* block */)handler;
- (id)registerNotificationHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (BOOL)unregisterNotificationHandler:(unsigned long long)handler;
- (void)sendNotification:(id)notification;
- (void)sendNotification:(id)notification waitForExecution:(BOOL)execution completionQueue:(id)queue completionBlock:(id /* block */)block;
@end

#endif /* SimNotificationManager_h */
