//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNearbyDeviceManager_h
#define SimNearbyDeviceManager_h
@import Foundation;

@class NSMutableDictionary, NSMutableSet;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimNearbyDeviceManager : NSObject

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSMutableSet *knownDevices;
@property (retain, nonatomic) NSMutableDictionary *bootedDevices;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *updateTimer;
@property (nonatomic) BOOL isTimerScheduled;
@property (nonatomic) unsigned long long updateMode;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)deviceSetCreated:(id)created;
- (void)_onQueue_checkDeviceSetForNewDevices:(id)devices;
- (void)_onQueue_addDevice:(id)device;
- (void)_onQueue_removeDevice:(id)device;
- (void)_onQueue_deviceDidBoot:(id)boot;
- (void)_onQueue_deviceDidShutdown:(id)shutdown;
- (void)_onQueue_peerDied:(id)died udid:(id)udid;
- (void)_onQueue_peerCheckedIn:(id)in discoveryToken:(id)token udid:(id)udid reply:(id)reply;
- (void)_onQueue_device:(id)queue_device connectedPeer:(id)peer;
- (BOOL)updateDevice:(id)device rect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect rotation:(double)rotation error:(id *)error;
- (void)_onQueue_scheduleUpdateIfNeededInMode:(unsigned long long)mode;
- (void)_onQueue_notifyPeersDeviceBoot:(id)boot;
- (void)_onQueue_notifyPeersDeviceShutdown:(id)shutdown;
- (void)_onQueue_notifyPeersNewTokenFromDevice:(id)device token:(id)token;
- (void)_onQueue_notifyPeersCancelTokenFromDevice:(id)device token:(id)token;
- (void)_onQueue_notifyPeersBroadcastFrom:(id)from payload:(id)payload;
- (void)_onQueue_updateTimerFired;
- (void)_onQueue_broadcastMessage:(id)message excluding:(id)excluding;
@end

#endif /* SimNearbyDeviceManager_h */
