//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNearbyPeer_h
#define SimNearbyPeer_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"

@class NSString;

@interface SimNearbyPeer : NSObject

@property (retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property (copy, nonatomic) NSString *discoveryToken;

/* instance methods */
- (id)initWithConnection:(id)connection discoveryToken:(id)token;
- (void)dealloc;
@end

#endif /* SimNearbyPeer_h */
