//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNotificationManagerToken_h
#define SimNotificationManagerToken_h
@import Foundation;

@interface SimNotificationManagerToken : NSObject

@property (copy, nonatomic) id /* block */ unregisterBlock;

/* class methods */
+ (id)tokenForManager:(id)manager registrationID:(unsigned long long)id;

/* instance methods */
- (id)initForManager:(id)manager registrationID:(unsigned long long)id;
- (void)dealloc;
- (void)invalidate;
@end

#endif /* SimNotificationManagerToken_h */
