//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimNSPasteboardItem_h
#define SimNSPasteboardItem_h
@import Foundation;

#include "SimPasteboardItem.h"
#include "SimPasteboardItemDataProvider-Protocol.h"

@class NSString, NSString",?;

@interface SimNSPasteboardItem : SimPasteboardItem<SimPasteboardItemDataProvider>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* instance methods */
- (id)initWithNSPasteboardItem:(id)item resolvedCount:(long long)count;
- (id)nsPasteboardRepresentation;
- (id)retrieveValueForSimPasteboardItem:(id)item type:(id)type;
@end

#endif /* SimNSPasteboardItem_h */
