//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimProfileBundle_h
#define SimProfileBundle_h
@import Foundation;

@class NSDictionary, NSString, NSURL;

@interface SimProfileBundle : NSObject

@property (nonatomic) struct __CFBundle * cfBundle;
@property (retain, nonatomic) NSURL *bundleURL;
@property (retain, nonatomic) NSString *bundlePath;
@property (retain, nonatomic) NSString *bundleIdentifier;
@property (retain, nonatomic) NSDictionary *infoDictionary;
@property (retain, nonatomic) NSDictionary *localInfoDictionary;
@property (retain, nonatomic) Class principalClass;
@property (nonatomic) void * binaryHandle;
@property (retain, nonatomic) NSString *infoPlistPath;
@property (nonatomic) struct timespec { long long x0; long long x1; } ctime;
@property (readonly, nonatomic) NSDictionary *fileToTimeMap;

/* class methods */
+ (id)extraCheckMap;
+ (id)bundleWithURL:(id)url error:(id *)error;
+ (id)bundleWithPath:(id)path error:(id *)error;
+ (id)bundleWithPath:(id)path loadBundle:(BOOL)bundle error:(id *)error;

/* instance methods */
- (id)initWithURL:(id)url error:(id *)error;
- (id)initWithURL:(id)url loadBundle:(BOOL)bundle error:(id *)error;
- (id)initWithPath:(id)path error:(id *)error;
- (id)initWithPath:(id)path loadBundle:(BOOL)bundle error:(id *)error;
- (void)dealloc;
- (BOOL)loadBundleWithError:(id *)error;
- (id)description;
- (id)pathForResource:(id)resource ofType:(id)type;
- (id)URLForResource:(id)resource withExtension:(id)extension;
- (id)objectForInfoDictionaryKey:(id)key;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (BOOL)isEqualToProfile:(id)profile;
- (unsigned long long)filesystemStatus;
@end

#endif /* SimProfileBundle_h */
