//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimPasteboardItemData_h
#define SimPasteboardItemData_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface SimPasteboardItemData : NSObject

@property (retain, nonatomic) NSString *type;
@property (retain, nonatomic) NSObject<NSSecureCoding> *value;

/* instance methods */
- (id)initWithType:(id)type value:(id)value;
@end

#endif /* SimPasteboardItemData_h */
