//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimPasteboardSyncPool_h
#define SimPasteboardSyncPool_h
@import Foundation;

#include "SimPasteboardSyncPoolProtocol-Protocol.h"

@class NSMapTable, NSUUID;
@protocol OS_dispatch_queue;

@interface SimPasteboardSyncPool : NSObject<SimPasteboardSyncPoolProtocol>

@property (retain, nonatomic) NSMapTable *pasteboards;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *processing_queue;
@property (retain, nonatomic) NSUUID *poolIdentifier;

/* instance methods */
- (id)init;
- (void)dealloc;
- (BOOL)addPasteboard:(id)pasteboard withError:(id *)error;
- (BOOL)removePasteboard:(id)pasteboard withError:(id *)error;
- (void)unregisterAndRemoveAll;
@end

#endif /* SimPasteboardSyncPool_h */
