//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimProfileModTime_h
#define SimProfileModTime_h
@import Foundation;

@interface SimProfileModTime : NSObject

@property (nonatomic) struct timespec { long long x0; long long x1; } ctime;

/* instance methods */
- (id)initWithTimeSpec:(struct timespec { long long x0; long long x1; })spec;
@end

#endif /* SimProfileModTime_h */
