//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimPasteboardItem_h
#define SimPasteboardItem_h
@import Foundation;

#include "NSPasteboardItemDataProvider-Protocol.h"

@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSPasteboardItem, NSString, NSString",?;

@interface SimPasteboardItem : NSObject<NSPasteboardItemDataProvider>

@property (readonly, copy, nonatomic) NSArray *internalRepresentation;
@property (retain, nonatomic) NSMutableDictionary *dataDictionary;
@property (retain, nonatomic) NSMutableArray *preferredOrderedTypes;
@property (retain, nonatomic) NSMapTable *promisedDataTypes;
@property (retain, nonatomic) NSPasteboardItem *nsPasteboardItem;
@property (nonatomic) BOOL typesAllResolved;
@property (readonly, copy, nonatomic) NSPasteboardItem *nsPasteboardRepresentation;
@property (readonly, copy, nonatomic) NSArray *types;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* class methods */
+ (id)itemFromNSPasteboardItem:(id)item options:(id)options;

/* instance methods */
- (id)init;
- (BOOL)setDataProvider:(id)provider forTypes:(id)types;
- (BOOL)setValue:(id)value forType:(id)type;
- (id)valueForType:(id)type;
- (void)pasteboard:(id)pasteboard item:(id)item provideDataForType:(id)type;
- (void)resolveAllTypes;
@end

#endif /* SimPasteboardItem_h */
