//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimPasteboardPortMap_h
#define SimPasteboardPortMap_h
@import Foundation;

@class NSMutableDictionary;

@interface SimPasteboardPortMap : NSObject {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (retain, nonatomic) NSMutableDictionary *portToProxyMap;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (id)description;
- (id)lookupWith:(unsigned int)with;
- (void)setValue:(id)value forPort:(unsigned int)port;
- (id)createPortKey:(unsigned int)key;
@end

#endif /* SimPasteboardPortMap_h */
