//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimRuntime_h
#define SimRuntime_h
@import Foundation;

#include "SimDeviceIORuntimeInterface-Protocol.h"
#include "SimLaunchHostClient.h"
#include "SimProfileBundle.h"
#include "SimRuntimePairingRequirements.h"

@class NSArray, NSDictionary, NSString, NSString",?, NSURL;
@protocol OS_dispatch_queue>",?;

@interface SimRuntime : NSObject<SimDeviceIORuntimeInterface>

@property (retain, nonatomic) SimProfileBundle *bundle;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *shortName;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) unsigned int version;
@property (nonatomic) unsigned int equivalentIOSVersion;
@property (copy, nonatomic) NSString *versionString;
@property (copy, nonatomic) NSString *buildVersionString;
@property (copy, nonatomic) NSString *root;
@property (copy, nonatomic) NSDictionary *supportedFeatures;
@property (copy, nonatomic) NSDictionary *supportedFeaturesConditionalOnDeviceType;
@property (copy, nonatomic) NSDictionary *requiredHostServices;
@property (copy, nonatomic) NSDictionary *forwardHostNotifications;
@property (copy, nonatomic) NSDictionary *forwardHostNotificationsWithState;
@property (copy, nonatomic) NSString *platformIdentifier;
@property (copy, nonatomic) NSString *resourcesPlatformIdentifier;
@property (copy, nonatomic) NSString *devicePlatformFolderName;
@property (copy, nonatomic) NSString *simulatorPlatformFolderName;
@property (copy, nonatomic) NSArray *supportedProductFamilyIDs;
@property (retain, nonatomic) SimRuntimePairingRequirements *pairingRequirements;
@property (copy, nonatomic) NSDictionary *environment_extra;
@property (retain, nonatomic) SimLaunchHostClient *launchHostClient;
@property (copy, nonatomic) NSArray *aliases;
@property (nonatomic) unsigned int minHostVersion;
@property (nonatomic) unsigned int maxHostVersion;
@property (nonatomic) unsigned int minCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int maxCoreSimulatorFrameworkVersion;
@property (copy, nonatomic) NSArray *supportedArchs;
@property (copy, nonatomic) NSArray *supportedArchStrings;
@property (copy, nonatomic) NSString *dyldSharedCachePath;
@property (nonatomic) BOOL supportsDyldSharedCache;
@property (retain, nonatomic) NSString *updateDyldBinaryPath;
@property (nonatomic) BOOL isInternal;
@property (retain, nonatomic) NSString *dyldSharedCacheBasePath;
@property (readonly, nonatomic) BOOL available;
@property (readonly, nonatomic) NSURL *runtimeRootURL;
@property (readonly, nonatomic) NSURL *bundleURL;
@property (readonly, nonatomic) NSURL *platformResourcesURL;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue>",? *memoizableSerializerQueue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString",? *debugDescription;

/* class methods */
+ (id)updatedMaxHostVersions;
+ (id)updatedMaxCoreSimulatorVersions;
+ (unsigned int)equivalentIOSVersionForVersion:(unsigned int)version profile:(id)profile platformIdentifier:(id)identifier;

/* instance methods */
- (id)initWithBundle:(id)bundle error:(id *)error;
- (id)environment;
- (id)platformResourcesPath;
- (id)bundlePath;
- (BOOL)supportsDeviceType:(id)type;
- (BOOL)supportsFeature:(id)feature;
- (BOOL)supportsFeatureConditionally:(id)conditionally;
- (BOOL)isEqualToRuntime:(id)runtime;
- (BOOL)isEqual:(id)equal;
- (long long)compare:(id)compare;
- (id)sampleContentPath;
- (BOOL)createInitialContentPath:(id)path error:(id *)error;
- (id)libLaunchURL;
- (BOOL)isAvailableWithError:(id *)error;
- (BOOL)rebuildDyldSharedCacheWithPolicy:(unsigned long long)policy error:(id *)error;
- (BOOL)gktoolScan:(id)scan error:(id *)error;
- (BOOL)resetDyldSharedCacheWithError:(id *)error;
- (id)deviceEquivalentPlatformIdentifier;
- (id)initForTest:(id)test;
@end

#endif /* SimRuntime_h */
