//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimRuntimePairingRequirements_h
#define SimRuntimePairingRequirements_h
@import Foundation;

@class NSArray;

@interface SimRuntimePairingRequirements : NSObject

@property (nonatomic) unsigned int minOSVersion;
@property (copy, nonatomic) NSArray *supportedProductFamilies;
@property (nonatomic) unsigned long long maxPairs;

/* instance methods */
@end

#endif /* SimRuntimePairingRequirements_h */
