//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.463, BuildCommit: 58445e79785a177ff4da5bb2a954f4f416f21788)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.4, Tool: ld (1053.12)
//    - LC_SOURCE_VERSION: 947.13.0.0.0
//
#ifndef SimVolumeManager_h
#define SimVolumeManager_h
@import Foundation;

#include "SimNotificationManager.h"
#include "SimServiceContext.h"

@protocol OS_dispatch_queue;

@interface SimVolumeManager : SimNotificationManager

@property (nonatomic) struct __DASession * session;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sessionQueue;
@property (retain, nonatomic) SimServiceContext *serviceContext;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)initCommonWithName:(id)name;
- (void)dealloc;
- (void)startSession;
- (BOOL)_shouldIgnoreDiskMountedAt:(id)at;
- (void)_diskAppeared:(struct __DADisk *)appeared diskDescription:(id)description reportConsequences:(BOOL)consequences addedDeveloperDir:(id)dir completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_disk:(struct __DADisk *)_disk propertiesChanged:(id)changed diskDescription:(id)description reportConsequences:(BOOL)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_diskDisappeared:(struct __DADisk *)disappeared diskDescription:(id)description reportConsequences:(BOOL)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (struct __DADissenter *)_diskUnmountApproval:(struct __DADisk *)approval diskDescription:(id)description;
- (BOOL)_sendUnmountNotificationWithDisk:(struct __DADisk *)disk timeout:(double)timeout reportConsequences:(BOOL)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)notifyCryptexWillUnmountForMountURL:(id)url;
@end

#endif /* SimVolumeManager_h */
